#######################################################################################
# Book settings
title: ""
logo: images/logo.png
author: The Jupyter Book Community
email: choldgraf@berkeley.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is an example book built with Jupyter Books.

exclude_patterns: [file-types/include-rst.rst]

execute:
  execute_notebooks: cache

parse:
  myst_extended_syntax: true

html:
  favicon: images/favicon.ico
  google_analytics_id: UA-52617120-7
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://jupyterbook.org/

repository:
  url: https://github.com/executablebooks/jupyter-book
  branch: master
  path_to_book: docs

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    panels_add_boostrap_css: False
    intersphinx_mapping:
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null

  extra_extensions:
    - sphinx_click.ext
    - sphinx_tabs.tabs
    - sphinx_panels
